### ISSUE TITLE
✨ SSW.com.au should have French and China flags in the mega menu (smaller screens)

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.MegaMenu#93]
Cc: @adamcogan @amankumarrr 

Hi team
  
### Pain
We don't have links to France / China on the menu - Tablet/Mobile view

### Suggested Solution

@adamcogan wants it after the SSW TV link as flags:

![Image](https://github.com/SSWConsulting/SSW.MegaMenu/assets/12601228/517ed00f-e229-4b75-bd86-017867182aa1)

Email thread: SSW.com.au should have French and China flags in the mega menu

### Tasks
- [x] 1. Add flags with links to ssw.fr and ssw.com.cn respectively 

Thanks!

**Comment by wicksipedia** [comment]
To be clear - the flags that are currently visible on desktops should be rendered in the responsive flyout

**Comment by tiagov8** [comment]
> To be clear - the flags that are currently visible on desktops should be rendered in the responsive flyout?

Correct. I updated the Issue to make it clear it's for smaller screens

**Comment by bettybondoc** [comment]
Cc @adamcogan @amankumarrr @wicksipedia @tiagov8

As per my chat with @Calinator444 and @jaydenalchin, I suggest displaying the language flag immediately upon landing on the page instead of hiding it behind the hamburger icon. From a user's perspective, landing on a page they don't understand can be confusing and may lead them to leave. However, seeing the flag icon immediately signals that a language option is available. This also makes it consistent with [ssw.fr](https://ssw.fr/) and [ssw.cn](https://ssw.cn/).

For [ssw.com.au](https://www.ssw.com.au/), I recommend we replace the search icon with the flag icon and move the search icon to the flyout menu.




![Image](https://github.com/user-attachments/assets/63caca05-4814-432d-8cc2-ab9e9f662801)


**Figure: ✅ Good Example - SSW China on mobile (flag with country codes)**




![Image](https://github.com/user-attachments/assets/77fc44ce-b9a0-461c-a6cb-8a4e5416b338)


**Figure: SSW France on mobile**



![Image](https://github.com/user-attachments/assets/de1cc679-5afe-4f42-9191-e9de04bef80d)


**Figure: SSW on mobile**

**Comment by Calinator444** [comment]
I ended up going with Betty's design for this. I've included screenshots in the pull request.

https://github.com/SSWConsulting/SSW.MegaMenu/pull/95

**Comment by Calinator444** [comment]
@wicksipedia 

Done - Here's the new UI in production

![Image](https://github.com/user-attachments/assets/bc342472-196e-4c58-b95a-c2a9975ff8b6)
